spring:
  application:
    name: bookstore

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  #jdbc:h2:tcp://localhost:9092/default
    driverClassName: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      platform: h2
#      schema-locations: classpath:sql/DDL.sql
#      data-locations: classpath:sql/DML.sql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console
