
CREATE TABLE book
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title    VARCHAR(255) NOT NULL,
    author   VARCHAR(255),
    price    DECIMAL DEFAULT 0,
    category VARCHAR(255),
    CONSTRAINT pk_book PRIMARY KEY (id)
);

ALTER TABLE book
    ADD CONSTRAINT uc_book_title UNIQUE (title);

CREATE TABLE cart
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT,
    book_id  BIGINT NOT NULL,
    title    VARCHAR(255) NOT NULL,
    price    DECIMAL DEFAULT 0,
    quantity INT DEFAULT 0,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);